// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDna5_W_EqonPbEBcifwSY6v6D1Q01gANo',
    appId: '1:436870160694:web:83e00a88399608af759397',
    messagingSenderId: '436870160694',
    projectId: 'firebasicz',
    authDomain: 'firebasicz.firebaseapp.com',
    storageBucket: 'firebasicz.appspot.com',
    measurementId: 'G-LRBV6GJ063',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7B7BfuR2FRU9vhpPovVWqXzJfvTD6WUI',
    appId: '1:436870160694:android:519ceac04d842bda759397',
    messagingSenderId: '436870160694',
    projectId: 'firebasicz',
    storageBucket: 'firebasicz.appspot.com',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHi4K6R9Y3tcg_YhF4ZZuvjDYjMaD1x8',
    appId: '1:436870160694:ios:9b072eec8a854bda759397',
    messagingSenderId: '436870160694',
    projectId: 'firebasicz',
    storageBucket: 'firebasicz.appspot.com',
    iosClientId: '436870160694-nec4fc2rnr6ggc1aln85u43t668k9ulh.apps.googleusercontent.com',
    iosBundleId: 'com.example.anbutekApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHi4K6R9Y3tcg_YhF4ZZuvjDYjMaD1x8',
    appId: '1:436870160694:ios:9b072eec8a854bda759397',
    messagingSenderId: '436870160694',
    projectId: 'firebasicz',
    storageBucket: 'firebasicz.appspot.com',
    iosClientId: '436870160694-nec4fc2rnr6ggc1aln85u43t668k9ulh.apps.googleusercontent.com',
    iosBundleId: 'com.example.anbutekApp',
  );
}
